//phase 1 report: results.json -> report.md + summary.json
//baseline = plain round(v/17) at 16 levels, which is what the host already does
//saving = bytes on each method's rd curve at the baseline's quality, 0 if the curve never gets there
import { readFileSync, writeFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'
import { DITHER_METHODS, quantize, type DitherMethod } from '../src/dither.ts'
import { crop, packGray4, QUADRANTS } from '../src/gray4.ts'
import { compressedSize } from '../src/lz4.ts'
import { decodePng } from '../sim/png.ts'
import { G2_FIT, frameMs, nominal } from '../sim/transport.ts'
import { LEVELS, BLUR_SIGMA, type Row } from './run.ts'

const root = join(dirname(fileURLToPath(import.meta.url)), '..')
const rows = JSON.parse(readFileSync(join(root, 'results/phase1/results.json'), 'utf8')) as Row[]

type Metric = 'msSsim' | 'ssim' | 'ssimBlur' | 'psnr'
const METRICS: { key: Metric; label: string }[] = [
  { key: 'msSsim', label: 'MS-SSIM' },
  { key: 'ssim', label: 'SSIM' },
  { key: 'ssimBlur', label: `SSIM after σ=${BLUR_SIGMA} px blur` },
  { key: 'psnr', label: 'PSNR' },
]
const PRIMARY: Metric = 'msSsim'
const GO_SAVING = 0.2
const GO_TYPES = 2

const types = [...new Set(rows.map((r) => r.type))]
const images = (t: string) => [...new Set(rows.filter((r) => r.type === t).map((r) => r.image))]
const get = (image: string, method: DitherMethod, levels: number) => rows.find((r) => r.image === image && r.method === method && r.levels === levels)!
const mean = (xs: number[]) => xs.reduce((s, v) => s + v, 0) / xs.length
const pct = (x: number, digits = 0) => `${(x * 100).toFixed(digits)} %`
const signed = (x: number) => `${x >= 0 ? '+' : '−'}${Math.abs(x * 100).toFixed(0)} %`

//cheapest bytes that reach q0, from the points or log-linear interp between neighbours
function bytesAtQuality(points: { q: number; b: number }[], q0: number): number | undefined {
  let best: number | undefined
  for (const p of points) if (p.q >= q0) best = Math.min(best ?? Infinity, p.b)
  for (let i = 0; i + 1 < points.length; i++) {
    const a = points[i]
    const c = points[i + 1]
    if ((a.q - q0) * (c.q - q0) < 0) {
      const t = (q0 - a.q) / (c.q - a.q)
      const b = Math.exp(Math.log(a.b) + t * (Math.log(c.b) - Math.log(a.b)))
      best = Math.min(best ?? Infinity, b)
    }
  }
  return best
}

interface FamilyResult {
  saving: number //unreachable counts as 0
  reached: number
  perImage: (number | undefined)[]
}

function familySavings(t: string, method: DitherMethod, metric: Metric, bytesKey: 'bytes' | 'bytesU32' = 'bytes', baselineMethod: DitherMethod = 'none'): FamilyResult {
  const perImage = images(t).map((img) => {
    const base = get(img, baselineMethod, 16)
    const points = LEVELS.map((l) => get(img, method, l)).map((r) => ({ q: r[metric], b: r[bytesKey] }))
    const b = bytesAtQuality(points, base[metric])
    return b === undefined ? undefined : 1 - b / base[bytesKey]
  })
  return { saving: mean(perImage.map((s) => Math.max(0, s ?? 0))), reached: perImage.filter((s) => s !== undefined).length, perImage }
}

//best method per image
function oracle(t: string, metric: Metric, bytesKey: 'bytes' | 'bytesU32' = 'bytes'): number {
  const fams = DITHER_METHODS.map((m) => familySavings(t, m, metric, bytesKey).perImage)
  return mean(images(t).map((_, i) => Math.max(0, ...fams.map((f) => f[i] ?? 0))))
}

function verdict(metric: Metric, bytesKey: 'bytes' | 'bytesU32' = 'bytes') {
  const perType = types.map((t) => {
    const fams = DITHER_METHODS.map((m) => ({ method: m, ...familySavings(t, m, metric, bytesKey) }))
    const best = fams.reduce((a, b) => (b.saving > a.saving ? b : a))
    return { type: t, best: best.method, saving: best.saving, reached: best.reached, oracle: oracle(t, metric, bytesKey) }
  })
  const passing = perType.filter((p) => p.saving >= GO_SAVING)
  return { metric, perType, passing: passing.map((p) => p.type), go: passing.length >= GO_TYPES }
}

const md: string[] = []
const table = (head: string[], body: (string | number)[][], align?: string[]) => {
  md.push(`| ${head.join(' | ')} |`)
  md.push(`|${head.map((_, i) => (align?.[i] ?? (i === 0 ? ':--' : '--:'))).join('|')}|`)
  for (const r of body) md.push(`| ${r.join(' | ')} |`)
  md.push('')
}

md.push('# Phase 1 benchmark results')
md.push('')
md.push(`Generated by \`npm run bench:report\` from \`results/phase1/results.json\` (${rows.length} variants: ${types.length} content types × 5 images × ${DITHER_METHODS.length} methods × ${LEVELS.length} level counts). Method and definitions: [docs/phase1-benchmark.md](../../docs/phase1-benchmark.md).`)
md.push('')

//baseline cost
md.push('## Baseline: what a full-screen frame costs today')
md.push('')
md.push('Plain 16-level quantization (the host\'s own conversion), four 288×144 containers, one LZ4 block each. Time per frame for four sequential sends.')
md.push('')
table(
  ['content', 'LZ4 bytes / frame', 'ratio vs. packed', 'G2 fit', '10 KB/s', '20 KB/s', '30 KB/s', 'MS-SSIM'],
  types.map((t) => {
    const base = images(t).map((i) => get(i, 'none', 16))
    const b = mean(base.map((r) => r.bytes))
    const ms = (m: Parameters<typeof frameMs>[1]) => `${(mean(base.map((r) => frameMs(r.containerBytes, m))) / 1000).toFixed(2)} s`
    return [t, Math.round(b).toLocaleString('en'), `${((576 * 288) / 2 / b).toFixed(1)}×`, ms(G2_FIT), ms(nominal(10)), ms(nominal(20)), ms(nominal(30)), mean(base.map((r) => r.msSsim)).toFixed(4)]
  }),
)

//dither cost at 16 levels
md.push('## What each dither costs at full depth (16 levels)')
md.push('')
md.push('Bytes relative to the baseline, mean over the type\'s images. Positive = more bytes than plain quantization.')
md.push('')
table(
  ['content', ...DITHER_METHODS.filter((m) => m !== 'none')],
  types.map((t) => [
    t,
    ...DITHER_METHODS.filter((m) => m !== 'none').map((m) => signed(mean(images(t).map((i) => get(i, m, 16).bytes / get(i, 'none', 16).bytes - 1)))),
  ]),
)

//rd tables
md.push('## Rate–distortion points (primary metric)')
md.push('')
md.push('Bytes relative to baseline / MS-SSIM, mean over the type\'s images.')
md.push('')
for (const t of types) {
  md.push(`<details><summary>${t}</summary>`)
  md.push('')
  table(
    ['method', ...LEVELS.map((l) => `${l} levels`)],
    DITHER_METHODS.map((m) => [
      m,
      ...LEVELS.map((l) => {
        const rs = images(t).map((i) => ({ r: get(i, m, l), b: get(i, 'none', 16) }))
        return `${pct(mean(rs.map((x) => x.r.bytes / x.b.bytes)))} / ${mean(rs.map((x) => x.r.msSsim)).toFixed(4)}`
      }),
    ]),
  )
  md.push('</details>')
  md.push('')
}

//savings at equal quality
const verdicts = METRICS.map((m) => verdict(m.key))
const primary = verdicts.find((v) => v.metric === PRIMARY)!
md.push('## Bytes saved at equal quality')
md.push('')
md.push(`Mean saving vs. the baseline at the baseline\'s ${METRICS.find((m) => m.key === PRIMARY)!.label}; in brackets, how many of the type\'s 5 images the method can match at all. "Per-image best" picks the best method for each image.`)
md.push('')
table(
  ['content', ...DITHER_METHODS, 'per-image best'],
  types.map((t) => [
    t,
    ...DITHER_METHODS.map((m) => {
      const f = familySavings(t, m, PRIMARY)
      return `${pct(f.saving)} (${f.reached})`
    }),
    pct(oracle(t, PRIMARY)),
  ]),
)

md.push('### Same, under the other metrics (best method per type)')
md.push('')
table(
  ['content', ...METRICS.map((m) => m.label)],
  types.map((t) => [t, ...verdicts.map((v) => {
    const p = v.perType.find((x) => x.type === t)!
    return `${pct(p.saving)} ${p.best} · best-per-image ${pct(p.oracle)}`
  })]),
)

//same thing with the u32 lz4 table
const u32 = verdict(PRIMARY, 'bytesU32')
md.push('### Robustness: LZ4 streaming table')
md.push('')
md.push('If the host used liblz4\'s streaming entry point (32-bit table) instead of `LZ4_compress_default`:')
md.push('')
table(
  ['content', 'best method (default)', 'saving', 'best method (u32)', 'saving'],
  types.map((t) => {
    const a = primary.perType.find((p) => p.type === t)!
    const b = u32.perType.find((p) => p.type === t)!
    return [t, a.best, pct(a.saving), b.best, pct(b.saving)]
  }),
)

//vs someone who already uses floyd-steinberg
md.push('### Versus a developer who already dithers with Floyd–Steinberg')
md.push('')
md.push('Baseline replaced by Floyd–Steinberg at 16 levels (common advice for 4-bit displays): saving of each method at FS-16\'s MS-SSIM.')
md.push('')
table(
  ['content', ...DITHER_METHODS],
  types.map((t) => [t, ...DITHER_METHODS.map((m) => {
    const f = familySavings(t, m, PRIMARY, 'bytes', 'floyd-steinberg')
    return `${pct(f.saving)} (${f.reached})`
  })]),
)

//side experiment: fold levels above 9 into 9
{
  const manifest = JSON.parse(readFileSync(join(root, 'corpus/manifest.json'), 'utf8')) as { type: string; file: string }[]
  const frameBytes = (levels: Uint8Array) =>
    QUADRANTS.reduce((n, r) => n + compressedSize(packGray4(crop({ width: 576, height: 288, levels }, r.x, r.y, r.width, r.height))), 0)
  const byType = new Map<string, { share: number[]; saving: number[] }>()
  for (const e of manifest) {
    const img = decodePng(new Uint8Array(readFileSync(join(root, 'corpus', e.file))))
    const q = quantize({ width: img.width, height: img.height, data: img.data }, { method: 'none', levels: 16 })
    const folded = q.levels.map((l) => Math.min(l, 9))
    const a = byType.get(e.type) ?? { share: [], saving: [] }
    a.share.push(q.levels.filter((l) => l > 9).length / q.levels.length)
    a.saving.push(1 - frameBytes(folded) / frameBytes(q.levels))
    byType.set(e.type, a)
  }
  md.push('## Side experiment: folding levels 10–15 into 9')
  md.push('')
  md.push('The simulator draws levels 9–15 identically (Phase 0), and g2-kit reports by eye that G2 brightness levels off around 8–10. If the panel truly saturates, levels above 9 can be sent as 9 at no visible cost. Same baseline, levels > 9 replaced by 9:')
  md.push('')
  table(
    ['content', 'pixels above level 9', 'bytes saved'],
    [...byType].map(([t, a]) => [t, pct(mean(a.share), 1), pct(mean(a.saving), 1)]),
  )
}

//go / no-go
md.push('## Go / no-go')
md.push('')
md.push(`Criterion (README): the best strategy saves at least ${pct(GO_SAVING)} of bytes at equal quality on at least ${GO_TYPES} content types. Primary metric: MS-SSIM.`)
md.push('')
table(
  ['metric', 'types passing', 'verdict'],
  verdicts.map((v) => [METRICS.find((m) => m.key === v.metric)!.label, v.passing.length ? v.passing.join(', ') : '—', v.go ? '**GO**' : 'no-go']),
)

writeFileSync(join(root, 'results/phase1/report.md'), md.join('\n'))
writeFileSync(
  join(root, 'results/phase1/summary.json'),
  JSON.stringify({ primary: PRIMARY, goSaving: GO_SAVING, goTypes: GO_TYPES, verdicts, u32 }, null, 1),
)
console.log(md.slice(md.indexOf('## Bytes saved at equal quality')).join('\n'))
